# Generated by Django 3.2.9 on 2021-12-12 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_message_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
