# Generated by Django 3.2.9 on 2021-12-05 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('for_date', models.DateField(blank=True, null=True)),
                ('credit', models.FloatField()),
                ('debit', models.FloatField()),
                ('units', models.FloatField()),
                ('my_subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.mysubscription')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
