# Generated by Django 3.2.9 on 2021-12-05 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='units',
            field=models.FloatField(default=0.0),
        ),
    ]
