# Generated by Django 3.2.9 on 2021-12-15 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20211212_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='paybill',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
